Description: >
  Ani Jeremiah / IAM Role/Policy for EC2 Instance to communicate with S3 Bucket
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  IAMRoleWebApp:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  IAMWebAppS3IP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRoleWebApp"

Outputs:
  IAMRoleWebApp:
    Description: "Allows EC2 instances to communicate with S3 bucket"
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${EnvironmentName}-MY-IAM
  IAMRoleWebAppArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt IAMRoleWebApp.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN